import Head from 'next/head'
import {Session} from "next-auth";
import {getProviders, getSession, useSession} from "next-auth/react";
import {signIn, signOut} from "next-auth/react";
import {useState} from "react";
import {NextPageContext} from "next";

export default function Home() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>
            Home
        </h1>
          
      </main>
    </>
  )
}
